#! /bin/bash
# curli - CLATTA - 2013-03-10
# Updated - CLATTA - 2014-06-20 - added var and if for agent
# Updated - CLATTA - 2015-04-10 - changed from HEAD req to a GET with dump header (D) 
# Updated - CLATTA - 2016-10-10 - added url encoding of spaces
# CURL SHORTCUT TO FOLLOW A URL AND GET ALL HEADERS ALONG THE WAY,
# THEN PRINT THE FINAL URL
if [ -z "$2" ]
    then
        agent='ADMIN_CURLI-20170421082518'
    else
        agent="$2"
fi
if [ -z "$3" ]
    then
        headers=""
    else
        headers="$3"
fi
url=$( echo "$1" | sed 's/ /%20/g' );
echo "${url}"
#curl $url -A "'$agent'" "$headers"  -s -L -I -w '%{url_effective}'
curl -A "'$agent'" -s -L -D  - "${url}" -o /dev/null -w '%{url_effective}'
echo ""
echo ""
