#!/bin/bash
# digit - minimal dig output
# CLATTA - Created 2009-10-01
# CLATTA - Updated 2015-04-28
# CLATTA - Name changed from mydig to digit  
input="$@"
#digout=`dig $input | grep -A9999999 'ANSWER SEC' | grep -v ';'`
digout=`dig +noall +answer ${input}`
if [ -z "$digout" ]
    then
        echo "No Answer for $input"
    else
        echo "$digout"
fi

