#!/bin/bash
# mydig - clatta - 2010-10-01
# Just a shortcut for a short answer from dig
# Updated - clatta - 2016-10-11 - optimized dig command
input="$@"
digout=`dig +noall +answer $@`
if [ -z "$digout" ]
    then
        echo "No Answer for $input"
    else
        echo "$digout"
fi

